package com.CTGUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.CTGUI.Controller;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author kimsj0302
 */
public class Ct_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Ct_Frame
     */
    public Ct_Frame() throws IOException {
        initComponents();
        cont = new Controller();
        jButton2.setEnabled(false);
        count = 0;
        cont.set_lb(left_bg1);
        cont.set_rb(right_bg1); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fSMGraph1 = new com.CTGUI.FSMGraph();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        scoreBoard2 = new com.CTGUI.ScoreBoard();
        jPanel2 = new javax.swing.JPanel();
        fSMGraph2 = new com.CTGUI.FSMGraph();
        resultBoard1 = new com.CTGUI.ResultBoard();
        fSMGraph3 = new com.CTGUI.FSMGraph();
        background2 = new com.CTGUI.background();
        left_bg1 = new com.CTGUI.left_bg();
        right_bg1 = new com.CTGUI.right_bg();
        jButton2 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(61, 23, 95));
        setPreferredSize(new java.awt.Dimension(1900, 1000));

        scoreBoard2.setBackground(new java.awt.Color(255, 255, 255));
        scoreBoard2.setBorder(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        left_bg1.setBorder(null);
        left_bg1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout left_bg1Layout = new javax.swing.GroupLayout(left_bg1);
        left_bg1.setLayout(left_bg1Layout);
        left_bg1Layout.setHorizontalGroup(
            left_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        left_bg1Layout.setVerticalGroup(
            left_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        right_bg1.setBorder(null);

        javax.swing.GroupLayout right_bg1Layout = new javax.swing.GroupLayout(right_bg1);
        right_bg1.setLayout(right_bg1Layout);
        right_bg1Layout.setHorizontalGroup(
            right_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        right_bg1Layout.setVerticalGroup(
            right_bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout background2Layout = new javax.swing.GroupLayout(background2);
        background2.setLayout(background2Layout);
        background2Layout.setHorizontalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(left_bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(right_bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        background2Layout.setVerticalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(left_bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(right_bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(fSMGraph2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultBoard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(background2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fSMGraph3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fSMGraph2, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fSMGraph3, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton2.setText("Next turn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu3.setText("menu");

        jMenuItem1.setText("quick result");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("setup");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("select boss");
        jMenu4.setToolTipText("");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("BOSS 1");
        jRadioButtonMenuItem1.setEnabled(false);
        jMenu4.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setText("BOSS 2");
        jMenu4.add(jRadioButtonMenuItem2);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(scoreBoard2, javax.swing.GroupLayout.PREFERRED_SIZE, 1714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scoreBoard2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Play One Turn */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try {
            /* FSM Graph */
            fSMGraph2.setCurrent(cont.game.getPlayer().getCurrentID() + 1, false);
            fSMGraph3.setCurrent(cont.game.getBoss().getCurrentID() + 1, false);
            fSMGraph2.repaint();
            fSMGraph3.repaint();
            fSMGraph2.revalidate();
            fSMGraph3.revalidate();

            /*
            Result board, setTurn. Record *BEFORE* play(), since game does not memorize previous states & outputs
                and play() makes the game steps forward.
             */
            resultBoard1.RecordResult(cont.game.getOngoingTurn(), cont.game.getPlayer().getAction(), cont.game.getBoss().getAction());
            System.out.println(cont.game.getPlayer().getAction());
            System.out.println(cont.game.getBoss().getAction());
            cont.command(cont.game.getPlayer().getAction(), cont.game.getBoss().getAction());
            cont.game.play();
            /* Score Board */
            scoreBoard2.setTurn(cont.game.getPreviousTurn());
            scoreBoard2.setPlayerScore(cont.game.getPlayer().getScore());
            scoreBoard2.setBossScore(cont.game.getBoss().getScore());

            if(++count == cont.game.getMAXTurn()) {
                jButton2.setEnabled(false);
            }

        } catch (Exception ex) {
            Logger.getLogger(Ct_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

   
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(jRadioButtonMenuItem2.isSelected()){
            JOptionPane.showMessageDialog(null, "2번 보스를 선택하였습니다.");
        }
        else{
            JOptionPane.showMessageDialog(null, "1번 보스를 선택하였습니다.");
        }
        cont.init_game(jRadioButtonMenuItem2.isSelected()?2:1);
        cont.game.resetGame();
        for(int i=0;i<10;i++){
            try {
                cont.game.play();
            } catch (Exception ex) {
                Logger.getLogger(Ct_Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try{
            cont.game.EndGame();
        } catch(Exception e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "출력이 완료되었습니다.");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            // TODO add your handling code here:
            cont.set_boss(jRadioButtonMenuItem2.isSelected()?1:0);
            
            /* Result Board */
            resultBoard1.ResetBoard();
            
            cont.init_game(jRadioButtonMenuItem2.isSelected()?2:1);
            cont.game.resetGame();
            
            /* Score Board */
            scoreBoard2.setPlayerName(cont.game.getPlayer().getName());
            scoreBoard2.setTurn(0);
            scoreBoard2.setPlayerScore(cont.game.getPlayer().getScore());
            scoreBoard2.setBossScore(cont.game.getBoss().getScore());
            
            /* FSM Graph */
            fSMGraph2.setGraph("src/main/java/files/player.txt");
            if(!jRadioButtonMenuItem2.isSelected())
                fSMGraph3.setGraph("src/main/java/files/boss1.txt");
            else
                fSMGraph3.setGraph("src/main/java/files/boss2.txt");
            fSMGraph2.repaint();
            fSMGraph3.repaint();
            fSMGraph2.revalidate();
            fSMGraph3.revalidate();
            jButton2.setEnabled(true);
            count = 0;
            //fSMGraph3.setGraph(null);
            cont.set_lb(left_bg1);
            cont.set_rb(right_bg1);
        } catch (IOException ex) {
            Logger.getLogger(Ct_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ct_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ct_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ct_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ct_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Ct_Frame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Ct_Frame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    private Controller cont;
    private int count;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.CTGUI.background background2;
    private com.CTGUI.FSMGraph fSMGraph1;
    private com.CTGUI.FSMGraph fSMGraph2;
    private com.CTGUI.FSMGraph fSMGraph3;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private com.CTGUI.left_bg left_bg1;
    private com.CTGUI.ResultBoard resultBoard1;
    private com.CTGUI.right_bg right_bg1;
    private com.CTGUI.ScoreBoard scoreBoard2;
    // End of variables declaration//GEN-END:variables
}
